[package]
name = "powershell-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
deadpool = { version = "0.9.5", default-features = false, features = ["unmanaged"] }
rand = "0.8.5"
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = ["macros", "io-util", "process", "rt"] }
